quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=echangelivre
quarkus.datasource.password=echangelivre
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/echangelivrebd

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql

mp.jwt.verify.issuer=https://echangelivre.fr
mp.jwt.verify.publickey.location=publicKey.pem
smallrye.jwt.sign.key.location=privateKey.pem

quarkus.swagger-ui.always-include=true

# Profil test
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/echangelivrebd
%test.quarkus.datasource.username=echangelivre
%test.quarkus.datasource.password=echangelivre
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.hibernate-orm.sql-load-script=no-file
%test.mp.jwt.verify.issuer=https://echangelivre.fr
quarkus.devservices.enabled=false